[2025-07-11T10:56:17.347+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Stage_events scheduled__2025-07-11T09:00:00+00:00 [queued]>
[2025-07-11T10:56:17.367+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Stage_events scheduled__2025-07-11T09:00:00+00:00 [queued]>
[2025-07-11T10:56:17.369+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-11T10:56:17.398+0000] {taskinstance.py:1350} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2025-07-11 09:00:00+00:00
[2025-07-11T10:56:17.407+0000] {standard_task_runner.py:57} INFO - Started process 3742 to run task
[2025-07-11T10:56:17.412+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Stage_events', 'scheduled__2025-07-11T09:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmp9p3ilzi3']
[2025-07-11T10:56:17.420+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask Stage_events
[2025-07-11T10:56:17.520+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Stage_events scheduled__2025-07-11T09:00:00+00:00 [running]> on host 0bd7d962c7d0
[2025-07-11T10:56:17.750+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-11T09:00:00+00:00'
[2025-07-11T10:56:17.752+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 46, in execute
    aws_hook = AwsHook(self.aws_credentials_id)
NameError: name 'AwsHook' is not defined
[2025-07-11T10:56:17.772+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Stage_events, execution_date=20250711T090000, start_date=20250711T105617, end_date=20250711T105617
[2025-07-11T10:56:17.797+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 4 for task Stage_events (name 'AwsHook' is not defined; 3742)
[2025-07-11T10:56:17.827+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-11T10:56:17.877+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
