[2025-07-11T14:17:46.907+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2025-07-11T14:17:43.101232+00:00 [queued]>
[2025-07-11T14:17:46.924+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Stage_events manual__2025-07-11T14:17:43.101232+00:00 [queued]>
[2025-07-11T14:17:46.925+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-11T14:17:46.946+0000] {taskinstance.py:1350} INFO - Executing <Task(StageToRedshiftOperator): Stage_events> on 2025-07-11 14:17:43.101232+00:00
[2025-07-11T14:17:46.954+0000] {standard_task_runner.py:57} INFO - Started process 237 to run task
[2025-07-11T14:17:46.957+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Stage_events', 'manual__2025-07-11T14:17:43.101232+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpz6w6_97a']
[2025-07-11T14:17:46.960+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask Stage_events
[2025-07-11T14:17:47.114+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Stage_events manual__2025-07-11T14:17:43.101232+00:00 [running]> on host 49f24e24a176
[2025-07-11T14:17:47.269+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-11T14:17:43.101232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-11T14:17:43.101232+00:00'
[2025-07-11T14:17:47.295+0000] {base.py:73} INFO - Using connection ID 'aws_credentials' for task execution.
[2025-07-11T14:17:47.299+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_credentials', conn_type='aws') credentials retrieved from login and password.
[2025-07-11T14:17:47.328+0000] {stage_redshift.py:53} INFO - Clearing data from destination Redshift table
[2025-07-11T14:17:47.398+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/stage_redshift.py", line 54, in execute
    redshift.run("DELETE FROM {}".format(self.table))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 117, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `` isn't defined
[2025-07-11T14:17:47.419+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Stage_events, execution_date=20250711T141743, start_date=20250711T141746, end_date=20250711T141747
[2025-07-11T14:17:47.448+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 9 for task Stage_events (The conn_id `` isn't defined; 237)
[2025-07-11T14:17:47.477+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-11T14:17:47.541+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
