[2025-07-14T02:22:58.880+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Create_tables manual__2025-07-14T02:22:55.976783+00:00 [queued]>
[2025-07-14T02:22:58.893+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Create_tables manual__2025-07-14T02:22:55.976783+00:00 [queued]>
[2025-07-14T02:22:58.894+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-07-14T02:22:58.908+0000] {taskinstance.py:1350} INFO - Executing <Task(CreateTablesOperator): Create_tables> on 2025-07-14 02:22:55.976783+00:00
[2025-07-14T02:22:58.916+0000] {standard_task_runner.py:57} INFO - Started process 508 to run task
[2025-07-14T02:22:58.920+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Create_tables', 'manual__2025-07-14T02:22:55.976783+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpq8xlpco1']
[2025-07-14T02:22:58.923+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask Create_tables
[2025-07-14T02:22:58.985+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Create_tables manual__2025-07-14T02:22:55.976783+00:00 [running]> on host d7ac0fd04b06
[2025-07-14T02:22:59.093+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='udacity' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-07-14T02:22:55.976783+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-14T02:22:55.976783+00:00'
[2025-07-14T02:22:59.111+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:01.268+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public.artists;
    CREATE TABLE public.artists (
	    artistid varchar(256) NOT NULL,
	    name varchar(256),
	    location varchar(256),
	    lattitude numeric(18,0),
	    longitude numeric(18,0)
    );
    , parameters: None
[2025-07-14T02:23:02.107+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:03.496+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public.songplays;
    CREATE TABLE public.songplays (
	    playid varchar(32) NOT NULL,
	    start_time timestamp NOT NULL,
	    userid int4 NOT NULL,
	    "level" varchar(256),
	    songid varchar(256),
	    artistid varchar(256),
	    sessionid int4,
	    location varchar(256),
	    user_agent varchar(256),
	    CONSTRAINT songplays_pkey PRIMARY KEY (playid)
    );
    , parameters: None
[2025-07-14T02:23:04.357+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:05.643+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public.songs;
    CREATE TABLE public.songs (
	    songid varchar(256) NOT NULL,
	    title varchar(256),
	    artistid varchar(256),
	    "year" int4,
	    duration numeric(18,0),
	    CONSTRAINT songs_pkey PRIMARY KEY (songid)
    );
    , parameters: None
[2025-07-14T02:23:06.436+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:07.755+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public.staging_events;
    CREATE TABLE public.staging_events (
	    artist varchar(256),
	    auth varchar(256),
	    firstname varchar(256),
	    gender varchar(256),
	    iteminsession int4,
	    lastname varchar(256),
	    length numeric(18,0),
	    "level" varchar(256),
	    location varchar(256),
	    "method" varchar(256),
	    page varchar(256),
	    registration numeric(18,0),
	    sessionid int4,
	    song varchar(256),
	    status int4,
	    ts int8,
	    useragent varchar(256),
	    userid int4
    );
    , parameters: None
[2025-07-14T02:23:08.538+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:09.898+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public.staging_songs;
    CREATE TABLE public.staging_songs (
	    num_songs int4,
	    artist_id varchar(256),
	    artist_name varchar(256),
	    artist_latitude numeric(18,0),
	    artist_longitude numeric(18,0),
	    artist_location varchar(256),
	    song_id varchar(256),
	    title varchar(256),
	    duration numeric(18,0),
	    "year" int4
    );
    , parameters: None
[2025-07-14T02:23:10.929+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:12.208+0000] {sql.py:375} INFO - Running statement: 
    DROP TABLE IF EXISTS public."time";
    CREATE TABLE public."time" (
	    start_time timestamp NOT NULL,
	    "hour" int4,
	    "day" int4,
	    week int4,
	    "month" varchar(256),
	    "year" int4,
	    weekday varchar(256),
	    CONSTRAINT time_pkey PRIMARY KEY (start_time)
    ) ;
    , parameters: None
[2025-07-14T02:23:13.257+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2025-07-14T02:23:15.016+0000] {sql.py:375} INFO - Running statement: 
    CREATE TABLE public.users (
	    userid int4 NOT NULL,
	    first_name varchar(256),
	    last_name varchar(256),
	    gender varchar(256),
	    "level" varchar(256),
	    CONSTRAINT users_pkey PRIMARY KEY (userid)
    );
    , parameters: None
[2025-07-14T02:23:15.377+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/create_tables.py", line 27, in execute
    redshift.run(exec_sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.DuplicateTable: Relation "users" already exists


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/create_tables.py", line 29, in execute
    self.log.error(f"'{self.table}' へのデータのロード中にエラーが発生しました: {e}")
AttributeError: 'CreateTablesOperator' object has no attribute 'table'
[2025-07-14T02:23:15.393+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=final_project, task_id=Create_tables, execution_date=20250714T022255, start_date=20250714T022258, end_date=20250714T022315
[2025-07-14T02:23:15.412+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 24 for task Create_tables ('CreateTablesOperator' object has no attribute 'table'; 508)
[2025-07-14T02:23:15.445+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-07-14T02:23:15.483+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
